### PR TITLE
Add logging for debugging purposes season

### PR DESCRIPTION
**Pull request by gewenyu99**
Duck season

### CODE REVIEW

**Comment by notVincentGe** [comment]
Hey tests aren't passing

**Comment by gewenyu99** [comment]
> Hey tests aren't passing

I took a look, I updated some text on the docs??? Why are the mobile e2e tests failing???

**Comment by notVincentGe** [comment]
> > Hey tests aren't passing
> 
> I took a look, I updated some text on the docs??? Why are the mobile e2e tests failing???

Probably flaky? Rerun the tests?

**Comment by gewenyu99** [comment]
> > > Hey tests aren't passing
> > 
> > 
> > I took a look, I updated some text on the docs??? Why are the mobile e2e tests failing???
> 
> Probably flaky? Rerun the tests?

I reran them, now the data ingest pipeline tests are failing. Plz send help

**Comment by notVincentGe** [comment]
> > > > Hey tests aren't passing
> > > 
> > > 
> > > I took a look, I updated some text on the docs??? Why are the mobile e2e tests failing???
> > 
> > 
> > Probably flaky? Rerun the tests?
> 
> I reran them, now the data ingest pipeline tests are failing. Plz send help

I reran it again, I think it's fixed.

**Pull request merged**
